#!/usr/bin/env bash

spaces (){
    WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')
    
    # Get workspaces with windows, showing only first 4 and any workspaces with windows
    seq 1 10 | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc '
        map(tostring) | 
        map({
            id: ., 
            windows: ($windows[.] // 0)
        }) |
        # Show first 4 workspaces
        .[:4] + 
        # Include workspaces with windows but after the 4th workspace
        map(select(.windows > 0)) | 
        unique'
}

spaces

socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
    spaces
done

